### PR TITLE
review request English subtitles #997 #984

### PR DESCRIPTION
**Pull request by muae**
제가 보기엔 번역의 의미가 분명하지 않은 것 같습니다.
[REVIEW] 라고 표시한 부분 한번 살펴봐주시면 감사하겠ㅅ브니다.

### CODE REVIEW

**Comment by MisunK** [comment]
이거 저한테 보내신 건가요? 번역 final review 는 김완준 거사님이 주로 하시는 것 같은데, 거사님께 부탁드리는게 좀 더 맞지 않을까 싶네요. ^^

**Comment by muae** [comment]
아니요. 김완준 거사님께 부탁드렸습니다. 그냥 diff 만드려고 생성한겁니다.

**Comment by MisunK** [comment]
아, 네. 알겠습니다~

**Comment by muae** [comment]
(from 김완준 거사님)

I took a look at it. Perhaps this would be better.

984
I don't wish to interfere in your life.  Why? To interfere would be to take responsibility for that decision, or at least to be partially responsible. I have hard enough time taking responsibility for my own life, and you are asking for me to be responsible for yours. So you can choose which option to follow.

997
This is what we are here to study. It is a different issue than being Buddhist or Christian because, fundamentally, Buddhism transcends religion. It is not one of the religions but transcends them.

**Pull request merged**
